---
# tasks file for jenkins

# - name: Check if you are installing on APT system
#   fail: msg="This role only supports Ubuntu or RHEL/CentOS for now"
#   when: (ansible_distribution_file_variety != "Debian") or
#         (ansible_distribution_file_variety != 'RedHat')

- name: Load OS specific environment variable files
  include_vars: "Debian.yml"
  when: ansible_os_family == 'Debian'

- name: Load OS specific environment variable files
  include_vars: "RedHat.yml"
  when: ansible_os_family == 'RedHat'

- name: install basic packages
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - git
    - vim
    - python
    - python-setuptools

- name: Add Addtional Groups
  group:
    name: "{{item}}"
    state: present
  with_items:
    - docker
    - jenkins

- name: Add Jenkins user
  user:
    name: jenkins
    shell: /bin/bash
    groups: docker,jenkins
    append: yes

- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Install awscli
  pip:
    name: awscli
    state: latest

- name: Enable execute on awscli
  file:
    path: "{{ path.awscli }}"
    mode: "u=rx,g=rx,o=rwx"

- import_tasks: tasks-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- import_tasks: tasks-Debian.yml
  when: ansible_os_family == 'Debian'
  static: no

- name: Install Docker CE
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - docker-ce

- name: Docker permissions for Vagrant
  user:
    name: vagrant
    shell: /bin/bash
    groups: docker
    append: yes

- name: Make sure Docker and Jenkins are running
  systemd: state=started name="{{item}}"
  with_items:
    - docker
    - jenkins






