---
# RedHat/CentOS specific tasks

- name: Ubuntu = Add Docker Repo Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: Ubuntu = Add Docker CE repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Ubuntu = Add Java webupd8team Repo for Java 8
  apt_repository:
    repo: 'ppa:webupd8team/java'
    state: present

- name: Ubuntu = Check if Oracle JDK is installed
  shell: dpkg-query -W -f='${Status}' oracle-java8-installer
  register: u_jdk_check
  ignore_errors: true
  failed_when: no
  changed_when: no

- name: Ubuntu = Accept Oracle Java 8 JDK License Agreement
  become: true
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when: u_jdk_check.rc == 1

- name: Ubuntu = Add Jenkins Repo Key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Ubuntu = Add Jenkins Repo
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present


- name: Ubuntu = Install Debian/Ubuntu packages - Java 8 and Jenkins
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - oracle-java8-set-default
    - oracle-java8-installer
    - oracle-java8-unlimited-jce-policy
    - jenkins


